import React, { useState } from 'react';
import ChatUI from './components/ChatUI';
import DoctorDashboard from './components/DoctorDashboard';
import { HeartPulse } from 'lucide-react';

function App() {
  const [view, setView] = useState('patient');
  
  // Dummy IDs for the demo
  const [PATIENT_ID] = useState(1);
  const [DOCTOR_ID] = useState(1);
  const [sessionId] = useState(`session-${Date.now()}`);

  return (
    <div className="min-h-screen bg-gray-100 font-sans text-gray-900 selection:bg-blue-200 pb-12">
      <nav className="bg-white shadow-sm border-b border-gray-200 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex flex-shrink-0 items-center space-x-2">
              <div className="bg-gradient-to-br from-blue-600 to-indigo-600 p-2 rounded-xl shadow-md">
                 <HeartPulse className="h-6 w-6 text-white" />
              </div>
              <span className="font-extrabold text-2xl tracking-tight text-gray-900">
                Medi<span className="text-blue-600">Flow</span> AI
              </span>
            </div>
            <div className="flex p-1 bg-gray-100 rounded-xl border border-gray-200 shadow-inner">
              <button 
                onClick={() => setView('patient')}
                className={`px-5 py-2 rounded-lg text-sm font-semibold transition-all duration-200 ${view === 'patient' ? 'bg-white shadow text-blue-700 ring-1 ring-gray-200' : 'text-gray-500 hover:text-gray-700'}`}
              >
                Patient Portal
              </button>
              <button 
                onClick={() => setView('doctor')}
                className={`px-5 py-2 rounded-lg text-sm font-semibold transition-all duration-200 ${view === 'doctor' ? 'bg-white shadow text-indigo-700 ring-1 ring-gray-200' : 'text-gray-500 hover:text-gray-700'}`}
              >
                Provider Portal
              </button>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-10">
        <div className="max-w-3xl mx-auto">
          {view === 'patient' ? (
            <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
              <div className="text-center mb-8">
                <h1 className="text-3xl font-extrabold text-gray-900 mb-3 tracking-tight">Book Your Appointment</h1>
                <p className="text-gray-600 max-w-xl mx-auto text-lg">Use our intelligent assistant to find local doctors, check availability, and book appointments instantly using natural language.</p>
              </div>
              <ChatUI patientId={PATIENT_ID} sessionId={sessionId} />
            </div>
          ) : (
             <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
              <div className="mb-8">
                 <h1 className="text-3xl font-extrabold text-gray-900 mb-2 tracking-tight">Provider Tools</h1>
                 <p className="text-gray-600 text-lg max-w-xl">Manage your schedule, define availability, and request patient performance analytics generated by MediFlow AI.</p>
              </div>
              <DoctorDashboard doctorId={DOCTOR_ID} />
            </div>
          )}
        </div>
      </main>
    </div>
  );
}

export default App;
